In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [3]:
df = pd.read_csv('report.N23.tsv', sep='\t')
df = df.sort_values(by="abundance", ascending=False)
df

,name,taxID,taxRank,genomeSize,numReads,numUniqueReads,abundance
1168,Canis lupus familiaris,9615,subspecies,2482000080,18669448,17135144,0.623155
1226,Bacteroides zoogleoformans,28119,species,3361794,3840,1112,0.093474
14703,Prevotella sp. E15-22,2937774,species,3335334,3190,1110,0.053459
5076,Porphyromonas crevioricanis,393921,species,2133352,20239,18471,0.030949
1594,Porphyromonas cangingivalis,36874,species,2404857,12874,9945,0.018487
...,...,...,...,...,...,...,...
6022,Rhodothermaceae,563843,family,0,9,0,0.000000
6023,Sphingomonas hankookensis,563996,species,3947172,1858,1115,0.000000
6024,Spirosoma rigui,564064,species,5828404,485,379,0.000000
6025,Ralstonia solanacearum MolK2,564065,strain,5586409,258,50,0.000000
17808,Thalassobellus,3400333,genus,0,1,0,0.000000